name: build-tool

# TODO: scope more tightly or something
on: [push]

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          orcadev.bat build-tool

      - uses: actions/upload-artifact@v3
        with:
          name: orca-win
          path: build/bin/orca.exe

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Build
        run: ./orcadev build-tool

      - uses: actions/upload-artifact@v3
        with:
          name: orca-mac-x64
          path: build/bin/orca

  build-macos-arm64:
    runs-on: [self-hosted, macos]
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Build
        run: ./orcadev build-tool

      - uses: actions/upload-artifact@v3
        with:
          name: orca-mac-arm64
          path: build/bin/orca
