name: build-tool

# TODO: scope more tightly or something
on: [push]

jobs:
  build-win:
    runs-on: windows-2022
    env:
      BUILD_OS: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Build
        id: build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          orcadev.bat build-tool
