name: create-release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build-tool.yaml

  release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      needs: build
      steps: 
        - uses: actions/download-artifact@v3
          with:
            # when name is not specified, all artifacts from this run will be downloaded
            path: releases
            merge-multiple: true # download all artifacts to directory specified by "path"
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "releases/*"


