name: create-release

on:
  push:
    tags:
       - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-tool:
    uses: ./.github/workflows/build-tool.yaml

  build-runtime:
    uses: ./.github/workflows/build-runtime.yaml

  release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      needs: [build-tool, build-runtime]
      steps: 
        - uses: actions/checkout@v4
          with: 
            path: repo
            sparse-checkout: |
              src
              resources

        - uses: actions/download-artifact@v4
          with:
            # when name is not specified, all artifacts from this run will be downloaded
            path: artifacts
            merge-multiple: true

        - name: Package CLI Tool
          run: |
            mkdir releases
            cp artifacts/orca.exe releases
            #cp artifacts/orca-mac-universal.tar releases

        - name: Package Windows Release
          run: |
            mkdir -p orca-${{ github.ref_name }}-win/bin
            mkdir -p orca-${{ github.ref_name }}-win/orca-libc
            mkdir -p orca-${{ github.ref_name }}-win/resources
            # gather source code
            cp -r repo/src orca-${{ github.ref_name }}-win
            # gather fonts
            cp repo/resources/* orca-${{ github.ref_name }}-win/resources
            # gather runtime
            cd artifacts
            tar -xzf orca-runtime-win.tar.gz
            cd ..
            cp artifacts/orca-runtime-win/bin/orca_runtime.exe orca-${{ github.ref_name }}-win/bin
            cp artifacts/orca-runtime-win/bin/orca.dll orca-${{ github.ref_name }}-win/bin

            # TODO(shaw): gather orca-libc once it is built by ci

            # generate checksum file
            find orca-${{ github.ref_name }}-win -type f -exec sha1sum {} + | LC_ALL=C sort | sha1sum > sha1.sum
            # create release tarball
            tar -czf orca-${{ github.ref_name }}-win.tar.gz orca-${{ github.ref_name }}-win sha1.sum
            mv orca-${{ github.ref_name }}-win.tar.gz releases

        - name: Package Mac x64 Release
          run: |
            mkdir -p orca-${{ github.ref_name }}-mac-x64/bin
            mkdir -p orca-${{ github.ref_name }}-mac-x64/orca-libc
            mkdir -p orca-${{ github.ref_name }}-mac-x64/resources
            # gather source code
            cp -r repo/src orca-${{ github.ref_name }}-mac-x64
            # gather fonts
            cp repo/resources/* orca-${{ github.ref_name }}-mac-x64/resources
            # gather runtime
            cd artifacts
            tar -xzf orca-runtime-mac-x64.tar.gz
            cd ..
            cp artifacts/orca-runtime-mac-x64/bin/orca_runtime  orca-${{ github.ref_name }}-mac-x64/bin
            cp artifacts/orca-runtime-mac-x64/bin/liborca.dylib orca-${{ github.ref_name }}-mac-x64/bin

            # TODO(shaw): gather orca-libc once it is built by ci

            # generate checksum file
            find orca-${{ github.ref_name }}-mac-x64 -type f -exec sha1sum {} + | LC_ALL=C sort | sha1sum > sha1.sum
            # create release tarball
            tar -czf orca-${{ github.ref_name }}-mac-x64.tar.gz orca-${{ github.ref_name }}-mac-x64 sha1.sum
            mv orca-${{ github.ref_name }}-mac-x64.tar.gz releases

        #- name: Package Mac arm64 Release
          #run: |
            #mkdir -p orca-${{ github.ref_name }}-mac-arm64/bin
            #mkdir -p orca-${{ github.ref_name }}-mac-arm64/orca-libc
            #mkdir -p orca-${{ github.ref_name }}-mac-arm64/resources
            ## gather source code
            #cp -r repo/src orca-${{ github.ref_name }}-mac-arm64
            ## gather fonts
            #cp repo/resources/* orca-${{ github.ref_name }}-mac-arm64/resources
            ## gather runtime
            #cd artifacts
            #tar -xzf orca-runtime-mac-arm64.tar.gz
            #cd ..
            #cp artifacts/orca-runtime-mac-arm64/bin/orca_runtime  orca-${{ github.ref_name }}-mac-arm64/bin
            #cp artifacts/orca-runtime-mac-arm64/bin/liborca.dylib orca-${{ github.ref_name }}-mac-arm64/bin

            ## TODO(shaw): gather orca-libc once it is built by ci

            ## generate checksum file
            #find orca-${{ github.ref_name }}-mac-arm64 -type f -exec sha1sum {} + | LC_ALL=C sort | sha1sum > sha1.sum
            ## create release tarball
            #tar -czf orca-${{ github.ref_name }}-mac-arm64.tar.gz orca-${{ github.ref_name }}-mac-arm64 sha1.sum
            #mv orca-${{ github.ref_name }}-mac-arm64.tar.gz releases

        - uses: ncipollo/release-action@v1
          with:
            artifacts: "releases/*"
