name: create-release

on:
  push:
    tags:
       - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-tool:
    uses: ./.github/workflows/build-tool.yaml

  build-runtime:
    uses: ./.github/workflows/build-runtime.yaml

  release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      needs: [build-tool, build-runtime]
      steps: 
        - uses: actions/checkout@v4
          with: 
            path: repo
            sparse-checkout: |
              src
              resources

        - uses: actions/download-artifact@v4
          with:
            # when name is not specified, all artifacts from this run will be downloaded
            path: artifacts
            merge-multiple: true

        - name: Package Windows Release
          run: |
            mkdir -p releases/orca-${{ github.refname }}-win/bin
            mkdir -p releases/orca-${{ github.refname }}-win/orca-libc
            mkdir -p releases/orca-${{ github.refname }}-win/resources

            # copy over source code
            cp -r repo/src releases/orca-${{ github.refname }}-win

            # copy over fonts
            cp repo/resources/* releases/orca-${{ github.refname }}-win/resources

            # copy over runtime
            tar -xzf artifacts/orca-runtime-win.tar.gz
            cp artifacts/orca-runtime-win/bin/orca_runtime.exe artifacts/orca-runtime-win/bin/orca.dll releases/orca-${{ github.refname }}-win/bin

            # TODO(shaw): copy over orca-libc once it is build by ci

            # generate checksum file
            cd releases/orca-${{ github.refname }}-win 
            find . -type f -exec sha1sum {} + | LC_ALL=C sort | sha1sum > sha1.sum

        - uses: ncipollo/release-action@v1
          with:
            artifacts: "releases/*"
